// Wild Magic Table

export const wildTable = ["Roll on this table at the start of each of your turns for the next minute, ignoring this result on subsequent rolls.",
"You expend all sorcery points, taking 1d6 force damage for each point lost. You gain temporary hit points equal to the damage taken for the next hour.",
"Roll on this table twice, ignoring this result on subsequent rolls.",
"You cast see invisibility on yourself.",
"A halo of letters appears around your head. For the next hour, you are aware if someone you can hear is lying.",
"For the next minute, any flammable object you touch that isn't being worn or carried by another creature bursts into flame. Giggling laughter can be heard from the fire.",
"You cast dragon's breath. The damage type is random.",
"You cast fireball as a 3rd-level spell centered on yourself.",
"You cast ice storm as a 4th-level spell centered on yourself.",
"You cast magic missile as a 5th-level spell.",
"You cast reduce on yourself.",
"Roll a d10. Your height changes by a number of inches equal to the roll. If the roll is odd, you shrink. If the roll is even, you grow.",
"Ill omen falls upon you. When making an ability check, attack roll, or saving throw, the DM may force you to roll with disadvantage once.",
"You cast confusion centered on yourself.",
"You cast hold person on a creature within 20 feet. If you choose no creature, you cast it on yourself.",
"For the next minute, you regain 5 hit points at the start of each of your turns.",
"For 10 minutes, you speak in a stranger's unusual voice. The voice is disruptive, but how it sounds is up to you.",
"You grow a long beard made of feathers that remains until you sneeze, at which point the feathers explode out from your face.",
"For the next minute, creatures within 30 feet of you gain 5 temporary hit points at the start of your turn. These hit points do not stack.",
"You cast grease centered on yourself.",
"Your hair turns bright pink.",
"The air charges with magic. Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.",
"You infuse creatures with magic. Creatures within 30 feet of you have advantage against the next effect that involves a saving throw.",
"Your skin turns a vibrant shade of blue. A remove curse spell can end this effect.",
"You encase yourself in a block of earth that fills all 5-foot spaces surrounding you. If a creature is in a space where the earth appears, they are pushed to the nearest unoccupied space. Each 5-foot section of the block has 20 hit points, and an AC of 17.",
"An eye appears on your forehead for the next hour. During that time, you have advantage on Perception checks that rely on sight.",
"Your hands become iron fists for the next minute. You cannot move your fingers, but your unarmed strikes deal 1d6 bludgeoning damage.",
"For the next minute, all your spells with a casting time of 1 action have a casting time of 1 bonus action.",
"You become slightly intoxicated and have difficulty concentrating. You have disadvantage on maintaining concentration on spells for the next hour.",
"You teleport up to 60 feet to an unoccupied space of your choice that you can see.",
"For the next minute, any spell you cast with that costs one action allows you to immediately fly 15 feet via magic winds that carry you briefly and deposit you on a surface. This movement doesn't provoke attacks of opportunity.",
"You are transported to the Astral Plane until the end of your next turn, after which time you return to the space you previously occupied or the nearest unoccupied space if that space is occupied.",
"You cast misty step, arriving at your location in a burst of delicious foods.",
"Maximize the damage of the next damaging spell you cast within the next minute.",
"Icy power swirls around you. For the next minute, you may cast ray of frost as a bonus action.",
"Roll a d10. Your age changes by a number of years equal to the roll. If the roll is odd, you get younger (minimum 1 year old). If the roll is even, you get older.",
"Your next damaging spell cast within the next minute creates a spectral fist that knocks the target(s) prone.",
"1d6 flumphs controlled by the DM appear in unoccupied spaces within 60 feet of you and are frightened of you. They vanish after 1 minute.",
"For the next hour, you leave a trail of flowers, fungi, and moss wherever you step.",
"You regain 2d10 hit points.",
"You switch positions with a creature of your choice within 60 feet in a puff of smoke.",
"You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all damage. If you drop to 0 hit points, your pot breaks, and your form reverts.",
"You cast grasping vine.",
"For the next minute, you can teleport up to 20 feet as a bonus action on each of your turns.",
"For the next minute, you are moved 5 feet in random direction at the end of each of your turns.",
"You cast levitate on yourself.",
"For the next hour, you can walk on walls and ceilings.",
"A unicorn controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.",
"A loud voice narrates your thoughts and actions for the next minute. It can be heard clearly from up to 100 feet away.",
"You can't speak for the next minute. Whenever you try, pink bubbles float out of your mouth.",
"You cry uncontrollably for the next minute. Whenever you try to speak, you hiccup wildly and snot shoots from your nose.",
"A spectral shield hovers near you for the next minute, granting you a +2 bonus to AC and immunity to magic missile.",
"A banana appears on your shoulder for the next minute. While holding the banana in your hand or mouth, you gain a +2 bonus to all saving throws.",
"You are immune to being intoxicated by alcohol for the next 5d6 days. A tattoo that says 'sober' appears on your forehead for the same amount of time.",
"Up to four creatures of your choice within 60 feet are knocked prone by a mysterious force.",
"Your hair falls out but grows back within 24 hours.",
"Your skin rots and decomposes. You gain disadvantage on all persuasion checks, but undead ignore you unless attacked. This can be alleviated via a greater restoration spell.",
"A modron chosen and controlled by the DM appears in an unoccupied space within 5 feet of you, then disappears 1 minute later.",
"You can speak with small animals for 1 hour. Birds and critters seek you to tell you random secrets they've acquired.",
"You regain your lowest-level expended spell slot.",
"Your eyes glow like multicolored lanterns for the next 24 hours.",
"For the next minute, you must shout when you speak.",
"You cast entangle centered on yourself.",
"You cast fog cloud centered on yourself.",
"You create a burst of psychic feedback to yourself and a creature within 60 feet. The creature takes 6d6 psychic damage and you are stunned until the end of your next turn.",
"Up to three creatures of your choice within 30 feet of you take 4d10 lightning damage.",
"An illusory copy of you appears. At the start of your next turn, it runs to the nearest creature you regard as an enemy within 60 feet and explodes, dealing 3d10 force damage in a 20 foot radius. If there is no enemy, it runs to you.",
"You percieve the nearest creature as saying something hurtful about you. You are frightened of that creature until the end of your next turn.",
"A random creature within 30 feet is charmed by you until the end of your next turn.",
"Each creature within 30 feet of you becomes invisible for the next minute. The invisibility ends on a creature when it attacks or casts a spell.",
"You no longer require food, other than at least one cup of tea a day. If you roll this outcome again, then you revert.",
"You gain resistance to all damage for the next minute.",
"You cast fear.",
"A random creature within 60 feet of you becomes poisoned for 1d4 hours. If they use an action to vomit and take 3d10 poison damage, then the poisoned condition ends.",
"You cast stoneskin on yourself. While the spell is active, your walking speed becomes 10 feet.",
"You glow with bright light in a 30-foot radius for the next minute. Any creature that ends its turn within 5 feet of you is blinded until the end of its next turn.",
"You cast speak with dead on the next corpse you touch.",
"You cast polymorph on yourself. If you fail the saving throw, you turn into a sheep for the spell's duration.",
"You cast bestow curse as a 5th-level spell on the next creature you touch.",
"Illusory butterflies and flower petals flutter in the air within 10 feet of you for the next minute.",
"A massive farting sound emenates from you. It is audible from 300 feet away.",
"You can take one additional action immediately.",
"Your tongue turns into silver. You speak and understand all languages for an hour.",
"Each creature within 30 feet of you takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt.",
"A burst of color erupts from you. Each creature within 30 feet of you heals 3d10 hit points, except you.",
"You cast mirror image.",
"You cast detect thoughts. This lasts for 1 hour and you do not need to concentrate to maintain the effect. Each time you use your action to focus, you take 1d6 psychic damage.",
"Toxic pustules grow on your body and explode. Creatures within 5 feet take 3d10 acid damage. For the next 1d6 days you have disadvantage on all Charisma checks.",
"You cast web.",
"You become invisible for the next minute. During that time, other creatures can't hear you. The invisibility ends if you attack or cast a spell.",
"You learn a random 1st level spell.",
"If you die within the next minute, you immediately come back to life as if by the reincarnate spell.",
"You become athletic. You have advantage on all strength, constitution, and dexterity checks for the next minute.",
"Your size increases by one size category for the next minute.",
"Charisma radiates from you for the next minute. You may use your action to strike a pose. A creature of your choice that can see you gains a d8 inspiration die that they may add to an attack roll, ability check, or saving throw. This die lasts until the end of the minute and does not stack if the creature already has one of these die.",
"You and all creatures within 30 feet of you gain vulnerability to piercing damage for the next minute.",
"Reroll, and you may spend 1 sorcery point to move one space up or down this table from the rolled result. You may pay this multiple times to move multiple spaces.",
"You are surrounded by faint, ethereal music for the next minute.",
"A pillar of wild magic explodes from you, and you regain all expended sorcery points.",
"You cast greater restoration on yourself and regain all lost hit points."
]